### ISSUE TITLE
Fact Checks - Please add Tool Tip for 2 Edit buttons and Delete Button

### ISSUE THREAD

**Issue by atomsalt** [factly/dega#564]
Fact Checks - Please add Tool Tip for 2 Edit buttons and Delete Button

**Comment by shreeharsha-factly** [comment]
@deshetti Instead of having two edit buttons. We can keep the quick edit button and remove another edit button so that we can navigate to the edit page by clicking the title.

**Comment by deshetti** [comment]
Let's have a tooltip as suggested by @sshankaramanchi instead of deleting the button. Let's keep the tooltips **only where required** for now where users might need more clarification on the buttons as in here.

Let's use the following terminology:
- Edit
- Quick Edit

Implement the same changes in the following places:

- [ ] Pages
- [ ] Posts
- [ ] Fact Checks

**Comment by deshetti** [comment]
@shreeharsha-factly I just noticed that none of the other entities has `Edit` button on the list pages. I guess that is why you were suggesting removing the `Edit` button. I stand corrected, lets remove the `Edit` button for consistency in all the list pages in that case and not worry about adding the tooltips as I suggested in the above comment.
